### ISSUE TITLE
Model.count() is not working

### ISSUE THREAD

**Issue by cope** [lucianmachado/sails-oracle-database#3]
Hey @lucianmachado,

As I mentioned in issue #2 we recently switched from sails-oracle-db to sails-oracle-database, and that now casues the Model.count() method to fail :(

This in turn ruins our paging functionality, of course...

```
Executing query:
SELECT COUNT(*) as count FROM (
	SELECT * FROM "MY_TABLE" WHERE (
		(upper("MY_TABLE"."NAME")LIKE $1) OR 
		(upper("MY_TABLE"."DESCRIPTION")LIKE $2) OR 
		(upper("MY_TABLE"."TYPE")LIKE $3) OR 
		(upper("MY_TABLE"."CREATED_BY")LIKE $4) OR 
		(upper("MY_TABLE"."CODE_NAME")LIKE $5) OR 
		(upper("MY_TABLE"."PRODUCT_FAMILY")LIKE $6) OR 
		(upper("MY_TABLE"."PROJECT_STATUS")LIKE $7) OR 
		(upper("MY_TABLE"."PRODUCT_ID")LIKE $8) OR 
		(upper("MY_TABLE"."PRODUCT_TYPE")LIKE $9) OR 
		(upper("MY_TABLE"."OWNER")LIKE $10)
	)
) AS "MY_TABLE"
count
Error (E_UNKNOWN) :: Encountered an unexpected error
: ORA-01036: illegal variable name/number

Details:  Error: ORA-01036: illegal variable name/number
```

Do you maybe have an idea why the count fails? :(

**Comment by lucianmachado** [comment]
Hello @cope,

I just published a fix to this issue, can you update your package to the latest version?

Regards!

**Comment by cope** [comment]
I use [0.3.0](https://www.npmjs.com/package/sails-oracle-database)
Is that the latest?

**Comment by cope** [comment]
I uninstalled and reinstalled, and the error is now different: `Details:  Error: ORA-00933: SQL command not properly ended`

**Comment by cope** [comment]
I found this on [stackoverflow](https://stackoverflow.com/a/46778011/271873).

I will trz to figure out in the [oracle-adapter](https://github.com/ryanwilliamquinn/oracle-adapter) code why it works...

**Comment by cope** [comment]
```
Executing query: SELECT COUNT(*) as count FROM (SELECT * FROM "MY_TABLE" ) AS "MY_TABLE"
Error (E_UNKNOWN) :: Encountered an unexpected error
: ORA-00933: SQL command not properly ended
```

I think I found the place where to fix it, looking further.

**Comment by cope** [comment]
Ah... I think you need to make a new npm release...

After uninstalling and reinstalling, my adapter.js still has the count method, even though here in the repository, the [adapter.js](https://github.com/lucianmachado/sails-oracle-database/blob/master/lib/adapter.js) file does not have it anymore.

Once I removed the count method from the adapter.js file, the count worked :)

So, I am 99% sure that all we need is a 0.3.2 release for npm :)

**Comment by lucianmachado** [comment]
@cope, can you try to update again? 

The latest version is 0.3.2, the package in the npmjs was outdated... my bad 😄

**Comment by cope** [comment]
Running npm update :) One sec...

**Comment by cope** [comment]
It works!!! :)
